baseURL = "https://bids-numpy.github.io/workshop_site_AIMS_2021/"
languageCode = "en-us"
title = "AMMI Scientific Python Workshop"
theme = "hugo-theme-learn"
canonifyURLs = true

[params]
  author = "Ross Barnowski"
  themeVariant = "blue"
  titleSeparator = " "
  disableLandingPageButton = true
